export const projects = [
  {
    title: 'Free Wordcloud Generator',
    description: "Personal Project - Free Wordcloud online is a free, open-source Web app that converts text into a wordcloud image, user friendly and responsive UI.",
    image: '/images/freeWordCloud.jpeg',
    tags: ['React.js',"Next.js", 'Html/CSS', "Boostrap",'API', "GA" ],
    source: 'https://github.com/emilioPonceAlvarado16/wordcloud-generator',
    visit: 'https://freewordcloud.netlify.app/',
    id: 0,
  },
  {
    title: 'BlockChain and agricultural products',
    description: "Track agricultural products from farms to end users using blockchain, raspberry's PI and node sensors.",
    image: '/images/blockChain_Isaias_Ponce.jpeg',
    tags: ['Python', 'Flask', 'BlockChain', "Raspberry",'html/css/Bs'],
    source: 'https://github.com/emilioPonceAlvarado16/Traceability-of-agricultural-products-using-blockchain',
    visit: 'http://www.idear.espol.edu.ec/sites/default/files/posters/edicion_x/telem%C3%A1tica_Cevallos_Carlos_Ponce_Isa%C3%ADas_Estudioparalaseguridadenlatrazabilidaddeproductosagr%C3%ADcolasusandoblockchaineninternetofthings.pdf',
    id: 1,
  },
  {
    title: 'Portfolio',
    description: "My personal portfolio using my favorite stack of technologies.",
    image: '/images/portfolio.jpeg',
    tags: ['React.js', 'Next.js',"Framer-motion", "css/html", "SEO"],
    source: 'https://github.com/emilioPonceAlvarado16/portfolio',
    visit: '/#',
    id: 2,
  },
  {
    title: 'Shrimp Pool',
    description: "Changing the pH of the water from the pool using step-motors, arduino, and sensors, send data to the cloud using the raspberry pi connection. (Shrimp Pool friendly)",
    image: '/images/shrimp_pool.jpeg',
    tags: ['C', 'Arduino', 'Raspberry Pi'],
    source: 'https://github.com/emilioPonceAlvarado16/sensors-shrimp-pool',
    visit: 'files/reporte_Ponce-1.pdf',
    id: 3,
  },
  {
    title: 'React Calculator',
    description: "This is a simple calculator using reactjs.",
    image: '/images/calculator.jpeg',
    tags: ['React.js', 'CSS', 'HTML'],
    source: 'https://github.com/emilioPonceAlvarado16/Calculator-app-react',
    visit: 'https://codesandbox.io/s/github/emilioPonceAlvarado16/Calculator-app-react/tree/main/?file=/src/App.js:2018-2106',
    id: 4,
  },
  {
    title: 'Game of life',
    description: "Simulates the life cycle depending of the type of the cell. Counts the number of new cells, death cells, average of death/new cells in every generation",
    image: '/images/game_of_life.jpeg',
    tags: ['C', 'Linux'],
    source: 'https://github.com/emilioPonceAlvarado16/Game-of-life',
    visit: '/images/game_of_life.jpeg',
    id: 5,
  },

];

export const TimeLineData = [
  { year: 2016, text: 'Started my journey as a new developer.', },
  { year: 2017, text: 'Worked intensively on ROMs & Kernels.', },
  { year: 2018, text: 'Learned Android app development.', },
  { year: 2019, text: 'Finished Diploma in Computer Engineering.', },
  { year: 2020, text: 'Got a scholarship from the Delhi government.', },
  { year: 2021, text: 'Still trying to figure out this weird year.', },
];